public with sharing class LeadTriggerHandler extends TriggerHandler {

     
    public override void beforeInsert() {
        try{
        }
        catch(Exception ex) {
           
            throw ex;
        }
    }
    
    
    public override void beforeUpdate() {
        try {
            
            for(Lead i : (List<Lead>) Trigger.new) {
               
            }

            for(Lead i : (List<Lead>) Trigger.new) {
               
              
            
        }
        }
        catch(Exception ex) {
           
            throw ex;
        }
    }

}